/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdio.h>

 int xs[3] = {0, 0, 0};

int main(void)
{
	printf("Hello world, Jaime!\n");
    /* Loop forever */

	int x=0, y=9, z=0;

	for (int i = 0; i < 10; i++) {
		x = x + i;
		y = y + x;
		z = y + x + z;
		xs[0] = x;
		xs[1] = y;
		xs[2] = z;
		printf("x=%d, y=%d, z=%d, w=%p\n", x, y, z, &xs);
	}

	void (*func)(void);
	func = (void*)0x00000009;
	func();
	printf("Done\n");
	for(;;);

}
