/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR 0x40023800UL
#define RCC_CFGR_OFFSET 0x08UL
#define CFGR_MCO1_BITS 21 // 21:22 (2 bits)
#define CFGR_MCO1_PRE_BITS 24 // 21:26 (3 bits)
#define RCC_CFGR_ADDR (RCC_BASE_ADDR+RCC_CFGR_OFFSET)

// RCC to enable GPIOA peripheral
#define RCC_ADDR 0x40023800UL
#define RCC_AHB1ENR_OFFSET 0x30UL // GPIOA peripheral is in AHB1 bus
#define RCC_AHB1ENR_ADDR (RCC_ADDR+RCC_AHB1ENR_OFFSET)
#define RCC_AHB1ENR_GPIOAEN_BIT 0

// GPIOA
// PA8 is Pin 67
#define GPIOA_AFRH_OFFSET 0x24UL
#define GPIOA_BASE_ADDR 0x40020000UL
#define GPIOA_AFRH_ADDR (GPIOA_BASE_ADDR + GPIOA_AFRH_OFFSET)
// AFRH8 = 8th bit = first 4 bits of AFRH

int main(void)
{

	// A. Select clock for MCO1 signal as HSI
	// 1. Bit21:22 = 00 == HSI clock selected, it's default but let's set it anyway
	uint32_t* pRccCfgrReg = (uint32_t*) RCC_CFGR_ADDR;
	*pRccCfgrReg |= (((uint32_t)0b11) << CFGR_MCO1_BITS); // is this needed?
	*pRccCfgrReg &= ~(((uint32_t)0b11) << CFGR_MCO1_BITS); // set 21, 22 bits to zero
	*pRccCfgrReg &= ~(((uint32_t)0b111) << CFGR_MCO1_PRE_BITS); // set 24:26 bits to zero
	// Prescaler 0b100 == /2
	*pRccCfgrReg |= ((uint32_t)0b100) << CFGR_MCO1_PRE_BITS;

	// B. Output MCO1 signal on MCU pin
	// 1. Enable GPIOA (Port A)
	uint32_t* pRccAhb1EnrReg = (uint32_t*) RCC_AHB1ENR_ADDR;
	*pRccAhb1EnrReg |= (1 << RCC_AHB1ENR_GPIOAEN_BIT);

	// 1.5 Enable alternate function mode
	uint32_t *pGpioaModeReg = (uint32_t*) (GPIOA_BASE_ADDR + 0);
	*pGpioaModeReg &= ~(0x3 << 16);
	*pGpioaModeReg |= (0b10 << 16);

	// 2. Configure GPIOA Pin 8 to AF0 (i.e. to output MCO1 signal)
	// Pin 8 is in GPIOA_AFRH
	// 2. Set AF0 on GPIO_AFRH8
	uint32_t* pGpioaAfrhReg = (uint32_t*) GPIOA_AFRH_ADDR;
	*pGpioaAfrhReg &= ~((uint32_t)0b1111); // first four bits (bit8) of port A set to 0000=AF0

    /* Loop forever */
	for(;;);
}
