/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"
#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                       \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void) {
  for (volatile uint32_t i = 0; i < 500000; i++)
    ;
}

int main(void) {
  printf("Hello SWO\n"); // not working with opencd
  // Enable FPU (set CP10 and CP11 to full access)
  // SCB->CPACR |= ((3UL << 10*2) | (3UL << 11*2));

  {
    // Task: Flash LED 4, PD12
    GPIO_PeriClockControl(GPIOD, ENABLE);
    GPIO_Handle_t gpioHandle;
    gpioHandle.pGPIOx = GPIOD;
    gpioHandle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
    gpioHandle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    gpioHandle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
    gpioHandle.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    gpioHandle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
    gpioHandle.GPIO_PinConfig.GPIO_PinAltFunMode = 0;
    GPIO_Init(&gpioHandle);
  }

  // Task 2: User button read mode
  {
    GPIO_PeriClockControl(GPIOA, ENABLE);
    GPIO_Handle_t gpioHandle;
    gpioHandle.pGPIOx = GPIOA;
    gpioHandle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
    gpioHandle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
    gpioHandle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
    gpioHandle.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    gpioHandle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
    gpioHandle.GPIO_PinConfig.GPIO_PinAltFunMode = 0;
    GPIO_Init(&gpioHandle);
  }

  /* Loop forever */
  for (;;) {
    if (GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == SET) {
      GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, SET);
    } else {
      GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, RESET);
    }
    // delay();
  }
}
