/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


// Enable ADC 1 Peripheral Scan flag
#define RCC_APB2ENR_OFFSET 0x44UL
#define RCC_BASE_ADDR 0x40023800UL
#define RCC_APB2ENR_ADDR (RCC_BASE_ADDR+RCC_APB2ENR_OFFSET)
#define RCC_APB2ENR_ADC1_BIT 8

// ADC1 peripheral CR1 SCAN bit
#define ADC_BASE_ADDR 0x40012000UL
#define ADC_CR1_OFFSET 0x04UL
#define ADC_CR1_SCAN_BIT 8
#define ADC_CR1_ADDR (ADC_BASE_ADDR+ADC_CR1_OFFSET)


int main(void)
{
	// Enable the peripheral clock for ADC1
	uint32_t* pRccApb2Enr = (uint32_t*) RCC_APB2ENR_ADDR;
	*pRccApb2Enr |= (1 << RCC_APB2ENR_ADC1_BIT);

	// Modify the ADC CR1 register (scan bit)
	uint32_t* pAdcCr1Reg = (uint32_t*) ADC_CR1_ADDR;
	*pAdcCr1Reg |= (1 << ADC_CR1_SCAN_BIT);


    /* Loop forever */
	for(;;);
}
